function koch(level)

% KOCH(LEVEL) Draw the Koch curve fractal. LEVEL denotes the number
% of iterations to perform.
% Example:
% koch(5);
% This file was generated by students as a partial fulfillment
% for the requirements of the course "Classical Mathematical
% Theorems and their Visualisation on the Computer", Winter term
% 2002/2003, Stuttgart University.
% Author : Dagmar Scherzinger, Carsten Reisser
% Date : Dec 2002
% Version: 1.0
if nargin ~= 1
error(['One input argument is required. Please type ' ...
'''help koch'' for usage information.']);
end
xl = zeros(10,1);
xr = xl;
yl = xl;
yr = yl;
xr(level) = 1;
r = sqrt(1/3^2 - 1/6^2);
clf;
set(gca,'FontSize',14);
set(gcf,'Color',[1,1,1]);

hold on;
subkoch(xl,xr,yl,yr,level,r);       % main drawing module
title('Koch Curve');
text(0.5,-0.05,(['Number of iterations: ' num2str(level)]), ...
'HorizontalAlign','center','FontSize',12);
hold off;
axis equal; axis tight; axis off;
%------------------------------------------------------------
end
